### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by eyal0** [gerbv/gerbv#100]
I've had good experiences with coveralls.io and it was free.

Code coverage is a nice tool in CI that will tell us if new code patches are getting good line coverage.  This is nice to have, it can identify holes in testing and give more confidence in PRs.

**Comment by eyal0** [comment]
I have opened a request with coveralls.io.  They will need permission to make comments on PRs so @ooxi might get an oauth email from coveralls.  I think that it's safe.  I use it on pcb2gocde.  You can see a sample of it here: https://coveralls.io/github/pcb2gcode/pcb2gcode?branch=master

And if you look in the PRs for that same repo, you'll see coveralls reporting on the coverage here and there.

**Comment by eyal0** [comment]
@ooxi If you'd like to do it yourself, you can do it here: https://coveralls.io/repos/new

**Comment by ooxi** [comment]
@eyal0 I agree having code coverage tests would be good

**Comment by eyal0** [comment]
Woohoo, check it out:

![image](https://user-images.githubusercontent.com/109809/160479308-620fb73d-5f2d-4e36-afa1-ff96a8ea17cf.png)

https://coveralls.io/builds/47760502

Pretty cool, I think.  This is a good start.

**Comment by ooxi** [comment]
This is great, thank you for adding Code Coverage support @eyal0!
