### ISSUE TITLE
Please bring back manual layer realignment feature

### ISSUE THREAD

**Issue by electroniceel** [gerbv/gerbv#106]
Older versions of gerbv (<2.7.0) had a feature to manually realign layers. It was accessible by right-clicking on a layer name and then choosing "Modify orientation" in the context menu. This brought up a dialog which allowed you to shift and scale the current layer by arbitrary numbers.

You can see screenshots and a description of the feature for example here: https://docs.oshpark.com/design-tools/gerbv/modify-orientation/

Current versions (2.7.0 to 2.8.2) don't have this anymore. There is now a "Align layers" menu options in the Edit menu. But it doesn't always work (sometimes gives me "Can't align by this type of object") and I prefer to being able to manually tune the alignment anyways.

Thanks.

**Comment by ooxi** [comment]
Unfortunately the screenshots on oshpark are of quite a low resolution, but they look similar to the *Edit Layer* dialog:

![gerbv edit layer](https://user-images.githubusercontent.com/2611835/163681454-1314a4ea-d6dc-4b63-b576-af8feb132f97.png)

Is this what you are looking for?

**Comment by electroniceel** [comment]
You are right, this is what I was looking for. Seems I didn't look closely enough.

Sorry to bother you.
