### ISSUE TITLE
Bottom side view

### ISSUE THREAD

**Issue by htot** [gerbv/gerbv#166]
It would be very useful if there would be "bottom side view" (vertical mirrored view) . This would allow to more easily compare the bottom layer with a real PCB.

**Comment by mikhailmihalkov** [comment]
So in the settings there is a rotation of file or what are you talking about?

**Comment by alexustas93** [comment]
Today for mirroring the bottom side you need go to the "Edit layer" and check the "Mirroring aout Y axis".
It's be more helpfull if the mirroring will be set on the toolbar and get the fast key (ex. "ctrl-M").

Also today the mirroring is not around the center of the board drawing. 
It's will be better if you will mirroring around the center of the board.

**Comment by htot** [comment]
@alexustas93 I see. I did not notice that as I just wanted to change the view, not edit the layer. But now I see there are buttons for "Apply to active" and "Apply to visible". Very useful to know.

So, yes what I was looking for would be "Apply to all" and "ctrl-M" as a shortcut would be very nice. Actually without changing coordinates (looking from the other side of an object does not change the coordinates of the object itself). And looking from top side we see a stack of layers top-down. Bottom side view would then be bottom-up.

Nevertheless "Apply to visible" does the trick nicely (and in some cases better). I like the red M icon too.

**Comment by ooxi** [comment]
@htot It seems that the shortcuts provided by @alexustas93 resolved your issue? Therefore I'm closing this issue.

Feel free to reopen if you would like further assistance!
