### ISSUE TITLE
This file doesn't render correctly, there's a big vertical line that's not really there.

### ISSUE THREAD

**Issue by cedric-airsupplies** [gerbv/gerbv#178]
I have the attached gerber file: [gto.zip](https://github.com/gerbv/gerbv/files/11650744/gto.zip)
When I open it in gerberv, it shows a big vertical line:
![image](https://github.com/gerbv/gerbv/assets/100704106/60d39756-290f-4ad9-96c7-7027c6c828ea)
When I open the same file in Kicad, the file is rendered correctly:
![image](https://github.com/gerbv/gerbv/assets/100704106/912f06d7-a657-49e2-bfc6-e5869143cd7c)

My versions:
Gerbv 2.9.7~742144 Compiled on May 25 2023 at 15:00:42
Windows 10 Home 21H2 19044.2965 64 bit

Application: KiCad Gerber Viewer x64 on x64
Version: 7.0.1, release build
Libraries:
	wxWidgets 3.2.2
	FreeType 2.12.1
	HarfBuzz 5.0.1
	FontConfig 2.14.1
	libcurl/7.83.1-DEV Schannel zlib/1.2.13
Platform: Windows 10 (build 19044), 64-bit edition, 64 bit, Little endian, wxMSW
Build Info:
	Date: Mar 11 2023 03:41:46
	wxWidgets: 3.2.2 (wchar_t,wx containers)
	Boost: 1.80.0
	OCC: 7.6.2
	Curl: 7.83.1-DEV
	ngspice: 39
	Compiler: Visual C++ 1934 without C++ ABI
Build settings:
	KICAD_SPICE=ON

**Comment by ooxi** [comment]
Thank you for the report @cedric-airsupplies, I'll try to reproduce!

**Comment by ooxi** [comment]
I have trouble reproducing the issue, does it only affect the High quality renderer or also Fast?

**Comment by cedric-airsupplies** [comment]
It takes a certain order of operations to produce the problem:
1) Start gerberv 64 bit.
2) File->Open-> browse to gto.
Now the problem is shown, with the following errors:
Number of parameters to aperture macro (103) are more than gerbv is able to store (102)
Number of parameters to aperture macro (107) are more than gerbv is able to store (102)
Number of parameters to aperture macro (105) are more than gerbv is able to store (102)
Number of parameters to aperture macro (103) are more than gerbv is able to store (102)
Number of parameters to aperture macro (109) are more than gerbv is able to store (102)
Number of parameters to aperture macro (103) are more than gerbv is able to store (102)
Number of parameters to aperture macro (103) are more than gerbv is able to store (102)
3) Click on Layers, and choose "reload layer". Now the gerber is shown correctly. (but gerberv generates again the errors in step 2)
4) Changing the view-> rendering does not show the problem again.
5) Set view -> rendering to normal, Click on Layers, and choose "reload layer". Now the problem is shown, with the errors from step 2
6) Set view -> rendering to fast XOR, Click on Layers, and choose "reload layer". Now the problem is shown, with the errors from step 2

**Comment by eyal0** [comment]
Are you using a version of gerbv that includes this fix:

https://github.com/gerbv/gerbv/pull/172

It may fix your error `Number of parameters to aperture macro (103) are more than gerbv is able to store (102)`

**Comment by cedric-airsupplies** [comment]
I have an older version. I'm planning to test this version that has the fix:
https://gerbv.github.io/ci/gerbv_2023-05-26_04c0ef_(Windows%20amd64).zip

**Comment by cdwijs** [comment]
It also happens on arch linux:
1) Make this package: https://aur.archlinux.org/packages/gerbv
2) Run gerbv, choose file-open-gto. (vieus already was view-fast XOR). This yields a correctly rendered image, and these errors:
Number of parameters to aperture macro (103) are more than gerbv is able to store (102)
Number of parameters to aperture macro (107) are more than gerbv is able to store (102)
Number of parameters to aperture macro (105) are more than gerbv is able to store (102)
Number of parameters to aperture macro (103) are more than gerbv is able to store (102)
Number of parameters to aperture macro (109) are more than gerbv is able to store (102)
Number of parameters to aperture macro (103) are more than gerbv is able to store (102)
Number of parameters to aperture macro (103) are more than gerbv is able to store (102)
3) Right click on the layer -> reload layer. This yields the incorrect image, and the errors from step 2

My versions:
$ uname -a
Linux cedric 6.3.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 05 Jun 2023 15:12:57 +0000 x86_64 GNU/Linux
$ gerbv --version
gerbv version 2.9.5
Copyright (C) 2001-2008 by Stefan Petersen
and the respective original authors listed in the source files.

**Comment by ooxi** [comment]
I do not doubt that this is happening, I just cannot reproduce it. It looks to me like some calculations resulted in NaN or infinity. I will try the Arch version.

**Comment by eyal0** [comment]
I am able to reproduce the bug.  When I first open the file, I get an empty screen or an all blue screen!  Weird.  But I can reproduce the error if click "Reload Layer" in the "Layer" menu and then I click on the "fit to screen" button.

![image](https://github.com/gerbv/gerbv/assets/109809/3715888d-8636-46ee-838b-7b37db7bfd12)

I used `git bisect`, running this command at each step:

`git clean -i -x -d && ./autogen.sh && ./configure --prefix=/home/esoha/.local && make -j 20 && make install && gerbv ~/Downloads/gto`

(The clean and all might be excessive but whatever.)

In the end, as suspected, the fix is in 1364c29ed048999dc7a060c4b7beeb48e09d9c05.  This is a newer version than your `Gerbv 2.9.7~742144`.

Are you able to upgrade to the new one?

**Comment by ooxi** [comment]
@eyal0 thank you for the bisect! I'll prepare the next release to get this patch into the public

**Comment by cedric-airsupplies** [comment]
The new release doesn't show the problem anymore on my windows machine. 
My versions:
Gerbv Version 2.9.8~2582ed Compiled on Jul  6 2023 at 19:34:41
Windows 10 Home 21H2 19044.2965 64 bit
I guess this bug can be closed.
