### ISSUE TITLE
Recommended Way to Report a Potential Security Issue

### ISSUE THREAD

**Issue by iosifache** [gerbv/gerbv#190]
Hi Gerbv team :wave:,

Could you please advise me where I should report a bug that may have a security impact? Unfortunately, there are no security policy or recommendations in `README.md`.

**Comment by iosifache** [comment]
Thanks for clarifying, @ooxi! Is there a possibility to add this observation in `README.md` or create a small `SECURITY.md` 🙏🏿?

**Comment by ooxi** [comment]
Thanks for the suggestion, will add to `README.md`

**Comment by iosifache** [comment]
Much appreciated, @ooxi 💯!
