### ISSUE TITLE
Set version to 2.8.0 and update NEWS

### ISSUE THREAD

**Issue by ooxi** [gerbv/gerbv#39]
The commit to be tagged as 2.8.0 should [set the version in `configure.ac`](https://github.com/gerbv/gerbv/blob/main/configure.ac#L25) and [update `NEWS`](https://github.com/gerbv/gerbv/blob/main/NEWS).

See 96e82fe9c1f235e2b8eb9422ab4659c188d96b75

**Comment by spe-ciellt** [comment]
I would suggest sending out an email to the gerbv-.devel mailing list to "report" the progress and urge people to send in their patches and bug fixes.

**Comment by ooxi** [comment]
I have published [pre-release 2.8.0-rc.1](https://github.com/gerbv/gerbv/releases/tag/gerbv-2-8-0-RC-1). If anybody has suggestions, especially with regards to the NEWS section, please let me know.

My plan is to publish 2.8.0 this weekend and inform the main distributions.

**Comment by ooxi** [comment]
[Release 2.8.0](https://github.com/gerbv/gerbv/releases/tag/v2.8.0) published.
