### ISSUE TITLE
gerbv doesn't parse Altium Excellon number format comments

### ISSUE THREAD

**Issue by neinseg** [gerbv/gerbv#97]
Here is an Excellon file that confuses gerbv's format auto-detection: 
[LimeSDR-QPCIe_1v2-RoundHoles.TXT](https://github.com/gerbv/gerbv/files/8009963/LimeSDR-QPCIe_1v2-RoundHoles.TXT)

This file is generated by Altium. Altium puts the number format of an excellon file inside a comment in the header like this:
```
;FILE_FORMAT=4:4
```

I think it would be worth it for gerbv to parse these comments and use them before guessing the number format.

**Comment by ooxi** [comment]
I agree with your observation. This issue was the reason I got involved in gerbv initially :-)

**Comment by eyal0** [comment]
How annoying!  Oh man, why can't everyone just follow the spec please?

I'll get to work.

**Comment by eyal0** [comment]
Before #101 :

![drill file before the changes](https://user-images.githubusercontent.com/109809/156298207-804de8fa-ef5b-470b-8870-4a53b83e5714.png)

After:

![drill file after the changes](https://user-images.githubusercontent.com/109809/156298288-1e04481e-a440-4da2-8249-0d2929cd8613.png)

Where did all the holes go?  Ah, have to zoom in:

![drill file after the changes and zoomed in to show some holes that are tiny](https://user-images.githubusercontent.com/109809/156298356-42121079-886d-4d59-a014-c5e63a741fa4.png)

Can someone confirm that it looks right?  Thanks.

**Comment by ooxi** [comment]
Thank you very much for implementing this! I have bumped the version to `2.9.0-dev` since this is a really useful feature
